#4 HeadsetDetection.m:9:33: error: no visible @interface for 'CDVPluginResult' declares the selector 'toSuccessCallbackString
#2 plugins.cordova.io will be deprecated in the near future